<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>appIcon.ico</ApplicationIcon>
    <Version>2.1.0</Version>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="WPF-UI" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\resources\icons\appIcon.png" Link="appIcon.png" />
  </ItemGroup>

</Project>
